[profile.default]
  evm_version = "london"
  fs_permissions = [{ access = "read-write", path = "./" }]
  libs = ["node_modules"]
  optimizer_runs = 200
  out = "out"
  solc-version = "0.8.20"
  src = "contracts"
